### ISSUE TITLE
core.exception.InvalidMemoryOperationError@(0)

### ISSUE THREAD

**Issue by yannick** [pszturmaj/ddb#44]
not sure if this is a ddb problem or vibe-d related ( @etcimon any ideas?).
but if you create a unittest block and you try to open a connection you get flooded with

 core.exception.InvalidMemoryOperationError@(0) 

messages

example:
https://github.com/yannick/ddb-vibe-exception

**Comment by etcimon** [comment]
Flooded with?

**Comment by pszturmaj** [comment]
try again with this dub.json:

{
	"name": "test",
	"description": "test",
	"dependencies": {
		"vibe-d": "~>0.7.24",
		"ddb": "~master"
	},
	"versions": ["VibeDefaultMain"]
}

**Comment by yannick** [comment]
that does the trick.is it the 2.067 fixes PR that solved it or something else?

**Comment by pszturmaj** [comment]
Yes, probably. Also there was a problem with date/time handling code.
