### ISSUE TITLE
PGCommand BOOLEAN parameter 

### ISSUE THREAD

**Issue by zafer06** [pszturmaj/ddb#50]
Hi,
I use ddb my vibe.d project and I run below code getting error?

```
PGCommand` cmd = new PGCommand(mConn);
cmd.query = "UPDATE test SET status = $1 WHERE id = $2";
cmd.parameters.add(1, PGType.BOOLEAN).value = true;
cmd.parameters.add(2, PGType.INT4).value = 105;
cmd.executeNonQuery();
``
```

**Comment by jacob-carlborg** [comment]
What kind of error do you get?

**Comment by zafer06** [comment]
I get this error;

```
Linking...
To force a rebuild of up-to-date targets, run again with --force.
Running ./tornet 
Listening for requests on http://::1:8081
Listening for requests on http://127.0.0.1:8081
Please open http://127.0.0.1:8081/ in your browser.
Task terminated with unhandled exception: Not implemented
Program exited with code -11
```

**Comment by jacob-carlborg** [comment]
I think you need to show some more of the code.

**Comment by zafer06** [comment]
I hope this is enough. 

```
import vibe.d;
import ddb.postgres;

shared static this()
{
	auto settings = new HTTPServerSettings;
	settings.port = 8080;
	settings.bindAddresses = ["::1", "127.0.0.1"];
	listenHTTP(settings, &hello);

	logInfo("Please open http://127.0.0.1:8080/ in your browser.");

	updateFlowers();
}

void updateFlowers()
{
	auto config = [
		"host" : "127.0.0.1",
		"database" : "postgres",
		"user" : "postgres",
		"password" : "12345"
	];

	auto conn = new PGConnection(config);

	auto cmd = new PGCommand(conn);
	cmd.query = "UPDATE flowers SET status = $1 WHERE id = $2";
	cmd.parameters.add(1, PGType.BOOLEAN).value = true;
	cmd.parameters.add(2, PGType.INT4).value = 5;
	cmd.executeNonQuery();

	logInfo("Successfull");
}

void hello(HTTPServerRequest req, HTTPServerResponse res)
{
	res.writeBody("Hello, World!");
}

/*
CREATE TABLE flowers
(
  id integer,
  name character varying(50),
  status boolean
)
*/
```
and output;

> zafer@zafer-pc ~/Projeler/d/ddb-error $ dub
> Performing "debug" build using dmd for x86_64.
> vibe-d:utils 0.7.27: target for configuration "library" is up to date.
> vibe-d:data 0.7.27: target for configuration "library" is up to date.
> vibe-d:core 0.7.27: target for configuration "libevent" is up to date.
> vibe-d:http 0.7.27: target for configuration "library" is up to date.
> vibe-d:diet 0.7.27: target for configuration "library" is up to date.
> vibe-d:mail 0.7.27: target for configuration "library" is up to date.
> vibe-d:mongodb 0.7.27: target for configuration "library" is up to date.
> vibe-d:redis 0.7.27: target for configuration "library" is up to date.
> vibe-d:web 0.7.27: target for configuration "library" is up to date.
> vibe-d 0.7.27: target for configuration "libevent" is up to date.
> ddb 0.2.4: target for configuration "library" is up to date.
> ddb-error ~master: building configuration "application"...
> Linking...
> To force a rebuild of up-to-date targets, run again with --force.
> Running ./ddb-error 
> Listening for requests on http://[::1]:8080/
> Listening for requests on http://127.0.0.1:8080/
> Please open http://127.0.0.1:8080/ in your browser.
> core.exception.AssertError@../../../.dub/packages/ddb-0.2.4/source/ddb/postgres.d(1127): Not implemented
> Program exited with code 1

**Comment by jacob-carlborg** [comment]
Looks like it's the bool that is the problem: `cmd.parameters.add(1, PGType.BOOLEAN).value = true;`. It's not implemented in the driver as the exception shows.

**Comment by claudiug** [comment]
any news on this issue, I also have it :|

**Comment by jacob-carlborg** [comment]
Sorry, no.
