### ISSUE TITLE
exception.d(679): Memory allocation failed

### ISSUE THREAD

**Issue by bubnenkoff** [pszturmaj/ddb#52]
I need to extract binary blob with `bytea` type from PG.

it was loaded there with command: 
`UPDATE "USERS" SET userblob = (pg_read_binary_file('img.png')::bytea) WHERE id>1;`

Original img.png have size 500KB.

On next code:

```
import std.stdio;
import ddb.postgres;

void main()
{
    auto conn = new PGConnection([
        "host" : "localhost",
        "database" : "test01",
        "user" : "postgres",
        "password" : "test"
    ]);

    scope(exit) conn.close;
	
	
	auto cmd = new PGCommand(conn);
	
	cmd.query = `SELECT name, userblob FROM "USERS" ;`;
	
	ubyte [] x;
	
	
	try {
       auto result = cmd.executeQuery;
	   
	   foreach (row; result)
	   {
		writeln(row[0]);
		x = row[1].get!(ubyte[]);  
	   }
	   
    }
    catch (ServerErrorException e) {
        // Probably table does not exist - ignore
    }

}
```
I am getting error: `Memory allocation failed`

**Comment by belka-ew** [comment]
Hm. I can't reproduce it on Linux 64bit, PostgreSQL 9.5.1 and dmd 2.068.2 and 2.71.0 with an image a bit smaller than your one.
Have you tried another files? What is your system, DB, compiler?
The query takes a bit long imho.

**Comment by bubnenkoff** [comment]
Thanks! I got answer from Etienne Cimon. He said that I need:"You should probably just do `scope(exit) dbres.destroy();` instead of `executeQuery!long().unique()`"
And now it's work!

http://forum.dlang.org/post/tzeneyvcqijkyslwptrv@forum.dlang.org
