### ISSUE TITLE
std.socketstream deprecation

### ISSUE THREAD

**Issue by belka-ew** [pszturmaj/ddb#58]
I thought last evening about the removing of std.socketstream from dmd 2.072. ddb can't be used now without vibe.d. I thought about the best solution to continue the ddb development and would like to present some ideas and get some opinions on them.

My suggestion is to use sockets directly in the way how libpq does. libpq has the ability to create blocking and non-blocking connections. The calls on non-blocking connections return immediately and it is the responsibility of the user to poll on the connection and wait for some result.
This would require some design changes and dropping the support of vibe.d. On the other hand it should be pretty straightforward to add vibe.d support on top of such API. The advantage is that it would make it possible to use ddb with other frameworks/event loops (important for my use case for example). Maybe we could provide some interfaces to integrate ddb in different applications.
I'm currently have nothing against vibe.d support in ddb, I would just move it into a different module.

I also thought about other alternatives. For example, low-level socket abstract API: functions that take ubyte[] and give back ubyte[], so the application itself can choose how to pass them to the sockets. Or add a dependency on a different stream library (the easest way undead.socketstream), but it would add an external dependency and nobody likes external dependencies. Or implementing streams directly in the ddb, that would require some unneeded work. So I'm still for the solution above.
@pinver, @jacob-carlborg

**Comment by pinver** [comment]
I'm currently using ddb via vibe.d core, so I would prefer a solution that don't involve a period of breakage of the vibe.d support.

Said that, IMHO, I would have integrated the functionality provided by streams directly in ddb, as a first step. I don't think that's unneeded work, as also if you go for a direct socket usage, you have to provide some scaffolding for converting ubyte[] into something more useful to digest.

Starting from that, it would be more clear how to add flexibility for supporting more mode of operations.

**Comment by jacob-carlborg** [comment]
I need ddb with vibe.d support as well. I think the simplest and fastest solution is to use `undead.socketstream` or just copy-paste it directly into ddb. That would give us some more time to come up with a better solution if needed.

**Comment by belka-ew** [comment]
Thanks for your feedback.
For now I've just moved the functionality from std.socketstream into PGStream since std.socketstream wasn't used much. vibe-d API is untouched.

In the case of proposing a breaking change I'll keep you current if it's ok for you. And a deprecation period is anyway a good thing.
