### ISSUE TITLE
executeRow throw exception if no result

### ISSUE THREAD

**Issue by bubnenkoff** [pszturmaj/ddb#65]
```
auto cmd = new PGCommand(pgconnection, sql.replace(`37.72308`, cargpspoint.lon).replace(`55.47957`, cargpspoint.lat));
	nearestroad = cmd.executeRow!NearestRoad;

```
I need to get from DB single Row but if there is not result `executeRow` throw Exception. Is there any way to do not trow exception?

**Comment by pszturmaj** [comment]
See docs for executeRow: http://pszturmaj.github.io/ddb/postgres.html

> Throws: Exception if result doesn't contain any rows or field count do not match. 

executeRow assumes that there is at least one row. You would need to use executeQuery instead.

**Comment by bubnenkoff** [comment]
is it's possible to do something like `.front` to get to access of only first Row?

auto nearestroad = cmd.executeQuery();
writeln(nearestroad.front);

or something like it?

**Comment by bubnenkoff** [comment]
I do not want to write foreach loop to get access for first row...

is it's possible?

**Comment by pszturmaj** [comment]
Yes, it should be possible to check for !empty() and then access the front(). You need to use proper types (see docs & examples).

**Comment by bubnenkoff** [comment]
But it's trow exception...

			auto cmd = new PGCommand(pgconnection, `SELECT * FROM "admin" where id=9111;`);
			try
			{
				writeln("test 1");
				auto nearestroad = cmd.executeQuery();
				writeln("test 2: ", typeid(nearestroad.front));
				writeln("test 3: ", typeid(nearestroad));
				//auto firstRow = nearestroad.map!(a=>a[0]);
				
			}

			catch(Exception e) // executeRow throw exeption if DB answer is empty
			{
				writeln(e.msg);
			}

The request is correct and return data.

Output:

```
test 1
Can't convert PostgreSQL's type 338872 to VariantN!20LU
```

**Comment by bubnenkoff** [comment]
Oh! This work!

				writeln("test 1");
				auto nearestroad = cmd.executeQuery();
				writeln("test 2: ", nearestroad.front);

test 1
test 2: [9111]

Thanks!

**Comment by bubnenkoff** [comment]
Only one question. How to make from:  [9111] --> 9111

**Comment by bubnenkoff** [comment]
Oh! That's work:
writeln("test 2: ", nearestroad.front[0]);
