### ISSUE TITLE
How create access to connection statment from many classes?

### ISSUE THREAD

**Issue by bubnenkoff** [pszturmaj/ddb#71]
I need to get access to connection starment from several classes. I am looking right way. I found one example in another driver
https://github.com/denizzzka/vibe.d.db.postgresql/blob/master/example/example.d
here is `shared` keyword is used.

Is it's good solution? Can I do same in with this driver?

**Comment by jacob-carlborg** [comment]
I would recommend using a thread local variable instead, that is, without the `shared` keyword and a connection pool.

**Comment by jacob-carlborg** [comment]
Something like:

```d
PostgresDB pool;

static this()
{
    pool = new PostgresDB([
        "host" : "localhost",
        "database" : "test",
        "user" : "postgres",
        "password" : "postgres"
    ]);
}
```

The call `pool.lockConnection` to get an instance of `PGConnection` each time you're executing a query.

**Comment by pinver** [comment]
Vibe.d documentation about `lockConnection` states:

>Note that, after retrieving a connection with lockConnection, the caller has to make sure that the connection is actually physically open and to reopen it if necessary. The ConnectionPool class has no knowledge of the internals of the connection objects.


As PGStream is private in PGConnection, what's the best suggested way for testing if the tcpConnection is alive? 

Is it acceptable to expose a new PGConnection method that check the embedded ConnectionStream connected property [1]?

Actually, if the returned connection has timed-out, an Exception is thrown...

[1] http://vibed.org/api/vibe.core.stream/ConnectionStream.connected

**Comment by jacob-carlborg** [comment]
> Is it acceptable to expose a new PGConnection method that check the embedded ConnectionStream connected property [1]?

Yes, that sounds a good idea. Perhaps even implement automatic reconnection if the connection is lost.

**Comment by pinver** [comment]
Frankly speaking, I'm looking at Vibe implementation of the ConnectionPool, and I've no clear idea of what to do with the closed connection: if it's a `TCPConnection`, how to `reopen it if necessary`?

I don't see also a way to remove it from the connection pool, or replace it with a new connection created with `connectTCP`...

Someone can take a look also in the Vibe documentation?

**Comment by jacob-carlborg** [comment]
If you do expose the `connected` method. What's the plan how to use it? I would assume it is to try to reconnect?

**Comment by pinver** [comment]
That was the plan, but I'm not finding a way to do it with the connection pool....

**Comment by pinver** [comment]
I've posted the problem in Vibe.d forums [[1]](https://forum.rejectedsoftware.com/groups/rejectedsoftware.vibed/thread/44097/), and it seems that the best way _actually_ to handle it is to wrap the Vibe.d TCPConnection and serve the wrapper in the connection pool.

In that way, the wrapper can just discard the closed wrapped TCPConnection with a new one, if it detects that the connection is closed (by the peer).

Is this acceptable? If yes, I'll try to provide a pull request for that.

**Comment by jacob-carlborg** [comment]
Yes.
